### ISSUE TITLE
Is it possible to support ordinal texts?

### ISSUE THREAD

**Issue by socieboy** [rmunate/SpellNumber#19]
It will be a good addition to this package.

**Comment by rmunate** [comment]
@socieboy Hello, could you provide me with some examples to understand more precisely what you are referring to?

**Comment by socieboy** [comment]
Basically a way to convert number like this:
1 = firsth
2= second
3 = third 

I was able to do this directly with php but it will be nice to have it wrapped on the package.

```
$formatter = new NumberFormatter('es_MX', NumberFormatter::SPELLOUT);
$formatter->setTextAttribute(NumberFormatter::DEFAULT_RULESET, "%spellout-ordinal-masculine");
$formatter->format(2); // second, segundo in spanish
```
Something like this:
```
SpellNumber::value(2)->toOrdinal();
SpellNumber::value(2, "%spellout-ordinal-masculine")->toOrdinal();
```

https://www.php.net/manual/en/class.numberformatter.php

**Comment by rmunate** [comment]
@socieboy Sounds like a really good feature, I'm adding it in the next release. 🚀🚀🚀

**Comment by rmunate** [comment]
@socieboy 
La versión esta lista para ser lanzada, crees que puedas revisar si podemos mejorarle algo?
Para que puedas instalar la versión de desarrollo, ejecuta el siguiente comando.

The version is ready to be released, do you think you can check if we can improve something?
So that you can install the development version, run the following command.

```bash
composer require rmunate/spell-number 1.0.x-dev
```

El manual ya se encuentra actualizado en:

The manual is already updated at:

**https://rmunate.github.io/SpellNumber/**

**_La estaré lanzando sobre las 17 Horas Bogotá, Colombia - 16 Horas CDMX, México_**

**Comment by socieboy** [comment]
Se ve bien! excelente, gracias!

**Comment by rmunate** [comment]
> Se ve bien! excelente, gracias!

En ese caso la lanzare de inmediato.
