### ISSUE TITLE
Review German

### ISSUE THREAD

**Issue by rmunate** [rmunate/SpellNumber#23]
@jetwes I hope you are well, I require your support to validate if the German language is correctly configured, I have received the following comment:

```php
SpellNumber::value(1000000.99)
    ->locale('de')
    ->currency('Euro')
    ->fraction('Cent')
    ->toMoney();
```

// Eine Million Von Euro Und Neunundneunzig Cent
As a german I can assure you there are some things wrong with this:

The replacement makes no sense. "Eine Million Von Euro" is grammatically incorrect and it should simply be "Eine Million Euro." Even if the "von" was correct it would have to be written in lowercase.
Capitalization is wrong. I found a Str::title(...) in the code that just capitalizes every word. This makes it easy but results in a wrong output as well. The "Eine" for example is correctly capitalized in case the output is at the beginning of a sentence but should be lowercased when it's not ("Eine Million [...] fehlen noch" but "Ich habe eine Million [...]"). Spellouts up to a million (but not including) are generally lowercased, so the output should/could be "Eine Million Euro und neunundneunzig Cent" (the "und" and "neunundneunzig" are lowercased).

Origin:
@dennisprudlo
https://github.com/dennisprudlo

**Comment by dennisprudlo** [comment]
Heyho, Dennis here 👋🏼

So I took a closer look and as you said in your comment in Laravels repository the underlying formatter is from the `intl` extension and should be correct. That's right.

https://github.com/rmunate/SpellNumber/blob/63e58a8d4c12b1cbcc08006f9bc4149920d19a72/src/SpellNumber.php#L278

Up to this point the output is correct (even with the lowercase `eine` so this string can be put in the middle of a sentence):
```php
"eine Million Euro und neunundneunzig Cent"
```

But the `Words::replaceLocale` right after that line returns a title cased version of the whole string which makes it incorrect (since the case matters in the german language) and adds the `Von` which makes it grammatically incorrect.
```php
"Eine Million Von Euro Und Neunundneunzig Cent"
```

I don't know about other languages but I think the `Str::title(...)` can be completely omitted because the `intl` extension returns the spellout with the right case as it appears ("Million" is uppercase and "neunundneunzig" is lowercase). I do think in polish the case matters as well so the title case would be wrong there too. If the title case is necessary for other languages one option would be to add an additional flag for the locale configs (whether to title case the result or not) but I guess completely removing it would be best.

Users can decide by themselves if they want to title case it. Title case can be used in german as well if you want to stylize a headline for example. But if the package does this automatically there is no way to get back to the correct casing for an inline string in a paragraph. Lowercasing the whole string would lowercase every word and the spellout is wrong again, since "Million" is required to be uppercase in any way.

Regarding the `Von`:
This is the correct literal translation of the english "of", yes, but it does not belong there at least for the german language. I am actually not sure if I ever heard someone saying "A million **_of_** dollars" in english as well. I am pretty sure "A million dollars" would be the correct spellout. But this is for a native english speaker to decide 😅

**Comment by AndrewMast** [comment]
Unrelated to the issue, but coming from the Laravel PR, I would recommend having this package optionally add a "helper" macro to Laravel's new Number class to utilize this package. The macro implementation could essentially be exactly what was added in the closed PR.

**Comment by rmunate** [comment]
Adjusted the class so that the output is in mioncase in all locales. In addition to removing the German language plug-in, please ensure you try version `rmunate/spell-number": "^4.2`

**Comment by dennisprudlo** [comment]
@rmunate Wouldn't this just result in the same problem with lowercased output? The changelog says
> In response to specific language nuances, output is now in lowercase. **_Developers have the option to modify the output as needed_**, keeping in mind the use of the callback function.

But is this really possible? The number from above will output `eine million euro und neunundneunzig cent` which is still wrong and you cannot really revert it to have the correct case, as I said here:
> But if the package does this automatically there is no way to get back to the correct casing for an inline string in a paragraph. Lowercasing the whole string would lowercase every word and the spellout is wrong again, since "Million" is required to be uppercase in any way.

What speaks against simply omitting the case transform? The `intl` extension outputs the value in the correct case, but any `toLower`, `toUpper`, `toTitle`, etc. will explicitly remove the correct case.
